More React Calculator Project - Milestone 5
SafaErden/React-Calculator pull request #5
Opened 2020-10-06 10:06 UTC by SafaErden

**In this milestone, I:**

- converted the App component to a class component,
- implemented the render function in the App component,
- passed the handle click method from the App component to ButtonPanel and Button components.

2020-10-06 14:51 UTC, shloch requested changes
## Hello @SafaErden 

This is some great work from you here...really great, you properly integrated the GUI and the logic
You are one step into getting thumbs-up except for the 'DIVISION BY ZERO' error
Look at the GIF below and debut and we'll be good to go
![calc](https://user-images.githubusercontent.com/40712459/95218027-c17f8180-07eb-11eb-95f2-3efe74396468.gif)

Happy coding

2020-10-06 14:51 UTC, shloch commented on src/logic/operate.js
> +      return undefined;
Hello, you handled DIVISION BY ZERO, but you did not bring it into display (in user-friendly manner) in the design.

In the design, you can display `Infinity` or `NaN` etc (something like that
(so that we don't get error above)

2020-10-06 19:50 UTC, mosesogwo requested changes
**Hello @SafaErden.. Well done on this:+1:**

:point_right: Please take note that when you divide by zero, the result shouldn't be zero. You can return undefined as a string so that it get's displayed properly.

_**Kindly make this change and submit another code review request.**_

**Cheers:stars:**

### Status: Changes Requested:exclamation:

2020-10-07 12:21 UTC, Torres-ssf approved these changes
### Milestone Approved :+1: 
Hi @SafaErden :hand: 
Great job working on the requested changes.
This PR is approved.

Happy Coding :computer: 
**Sergio Torres**

2020-10-07 12:31 UTC, merged